//@version=5

// @description Provides Risk Management related functions.
library("RiskManagementBeta", true)

// —————————— PineCoders MTF Selection Framework functions
// ————— Converts current "timeframe.multiplier" plus the TF into minutes of type float.
f_resInMinutes() =>
    _resInMinutes = timeframe.multiplier * (
      timeframe.isseconds ? 1. / 60. :
      timeframe.isminutes ? 1.       :
      timeframe.isdaily   ? 1440.    :
      timeframe.isweekly  ? 10080.   :
      timeframe.ismonthly ? 43800.   : na)

getResolutionBarMinutes(resolution) =>
    currentResInMinutes = f_resInMinutes()
    minutes = resolution == '1' ? (1 * 1) :
     resolution == '3' ? (3 * 1) :
     resolution == '5' ? (5 * 1) :
     resolution == '15' ? (15 * 1) :
     resolution == '30' ? (30 * 1) :
     resolution == '45' ? (45 * 1) :
     resolution == '60' ? (60 * 1) :
     resolution == '120' ? (2 * 60) :
     resolution == '180' ? (3 * 60) :
     resolution == '240' ? (4 * 60) :
     resolution == '1D' ? (24 * 60) :
     resolution == '1W' ? (7 * 24 * 60) :
     resolution == '1M' ? (4 * 7 * 24 * 60) :
     currentResInMinutes // Equal to current symbol
    minutes

getCurrentPeriod (_period) =>
    periodMinutes = getResolutionBarMinutes(_period)
    barMinutes = getResolutionBarMinutes(timeframe.period)
    barMinutesToNow = bar_index * barMinutes
    currentPeriod = math.floor(barMinutesToNow / periodMinutes)

// @function Returns current day number from strategy start
// @returns Current day number from strategy start
export getCurrentDay () =>
    getCurrentPeriod ('1D')

// @function Returns current week number from strategy start
// @returns Current week number from strategy start
export getCurrentWeek () =>
    getCurrentPeriod ('1W')

// @function Returns current month number from strategy start
// @returns Current month number from strategy start
export getCurrentMonth () =>
    getCurrentPeriod ('1M')
